#!/usr/bin/bash
file=$1
filename=$(basename -- "$file")
extension="${filename##*.}"
images="png jpg_ jpeg webp" # extensiones de formato imagen

if [[ "$extension" == "pdf" ]]; then
    pdftotext "$@" -
elif [[ "$images" =~ "$extension" ]]; then
    chafa "$file"
else
    bat=/usr/bin/bat
    if [[ -f "$bat" ]]; then
        bat --color=always -p "$file"
    else
        cat $file
    fi
fi
