#!/usr/bin/env bash

SIGNAL=5
SERVICE="inhibit-idle.service"
NOTIFICATION_ICON="/usr/share/icons/Qogir/symbolic/status/windows-quick-list-symbolic.svg"

# ==================== TOGGLE ====================
if [[ "$BLOCK_BUTTON" == "1" ]]; then
    if systemctl --user is-active --quiet "$SERVICE"; then
        systemctl --user stop "$SERVICE"
        notify-send "Modo Proyección" "Desactivado" -i "$NOTIFICATION_ICON" -u low
    else
        systemctl --user start "$SERVICE"
        notify-send "Modo Proyección" "Activado" -i "$NOTIFICATION_ICON" -u low
    fi

    pkill -RTMIN+$SIGNAL i3blocks 2>/dev/null
fi

# ==================== ESTADO ====================
if systemctl --user is-active --quiet "$SERVICE"; then
    icon="󰹁 "
    text="ON"
    color="#BD93F9"
else
    icon="󰹂 "
    text="OFF"
    color="#6272A4"
fi

echo "$icon $text"
echo "$icon"
echo "$color"
