
# bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

# bind-key -r G run-shell "~/.local/bin/tmux-sessionizer ~/work/nrdp"
# bind-key -r C run-shell "~/.local/bin/tmux-sessionizer ~/work/tvui"
# bind-key -r R run-shell "~/.local/bin/tmux-sessionizer ~/work/milo"
# # bind-key -r L run-shell "~/.local/bin/tmux-sessionizer ~/work/hpack"
# bind-key -r H run-shell "~/.local/bin/tmux-sessionizer ~/personal/vim-with-me"
# bind-key -r T run-shell "~/.local/bin/tmux-sessionizer ~/personal/refactoring.nvim"
# bind-key -r N run-shell "~/.local/bin/tmux-sessionizer ~/personal/harpoon"
# bind-key -r S run-shell "~/.local/bin/tmux-sessionizer ~/personal/developer-productivity"

# --------------- NEW --------------------
# Configured by Rob Muhlestein (rwxrob.live)
# This file is copyright free (public domain).

# fix accidently typing accent characters, etc.
# by forcing the terminal to not wait around
# (every single tmux file should have this)
set -sg escape-time 0

# change default meta key 
unbind C-b
unbind C-a
set -g prefix C-e

unbind m
bind-key -r m run-shell "cht.sh"


# form vim/tmux d/y buffer sync
set -g focus-events

# use a different prefix for nested
bind-key -n C-y send-prefix

# add double-tap meta key to toggle last window
bind-key C-e last-window


# Colors and display
set -g status on
setw -g mouse on
#term colors
set -ag terminal-overrides ",xterm-256color:RGB"
set -g default-terminal "screen-256color"
set -ag terminal-overrides ",alacritty:RGB"
set -g clock-mode-style 24
set -g base-index 1
setw -g pane-base-index 1

# color of the window selection background
set -g mode-style "bg=default"
set -g mode-style "fg=#F89328"

# colors 
set -g pane-border-style "fg=#444444"
set -g pane-active-border-style "fg=#666666"

# set -g status-style 'bg=#333333 fg=#5eacd3'
set -g status-style 'fg=#5eacd3'
set -g status-bg default 
set -g message-style "fg=red"

set -g status-bg default
set -g status-position bottom
set -g status-interval 2

# status line
set -g status-justify right
set -g status-left "[#S]"" #{=21:pane_title}"
set -g status-left-length 10
set -g status-left-style default
set -g status-right " %H:%M %d-%b-%y"
set -g status-right-length 40
set -g status-right-style default

# create more intuitive split key combos (same as modern screen)
unbind |
bind | split-window -h
unbind -
bind - split-window -v

# kill current window and all panes
bind-key & kill-window
unbind x
bind-key x kill-window
bind-key C-r choose-window
bind-key C-c new-window

# vi for copy mode
setw -g mode-keys vi

# vi for command status
set -g status-keys vi

# vi keys to resize
bind -r C-k resize-pane -U 1
bind -r C-j resize-pane -D 1
bind -r C-h resize-pane -L 1
bind -r C-l resize-pane -R 1

# vi keys to navigate panes
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# avoid cursor movement messing with resize
set -g repeat-time 200

# reload configuration
bind -r R source-file ~/.config/tmux/tmux.conf

