# [flavor]
# dark = "gruvbox-dark"
# light = "gruvbox-dark"

[preview]
hovered       = { underline = false, bg = "#484D66"}

[status]
# separator_open = "\ue0be"
# separator_close = "\ue0b8"
separator_open = " "
separator_close = " "
separator_style = { fg = "#3c3836", bg = "#3c3836" }

# Progress
progress_label = { fg = "#ebdbb2", bold = true }
progress_normal = { fg = "#504945", bg = "#3c3836" }
progress_error = { fg = "#fb4934", bg = "#3c3836" }

[mode]
normal_main = { fg = "#282828", bg = "#a89984", bold = true }
normal_alt = { fg = "#dddddd", bg = "#555555", bold = true }

select_main = { fg = "#282828", bg = "#fe8019", bold = true }
select_alt = { fg = "#dddddd", bg = "#555555", bold = true }

unset_main = { fg = "#282828", bg = "#b8bb26", bold = true }
unset_alt = { fg = "#dddddd", bg = "#555555", bold = true }

[icons]

"Desktop/"     = ""
"Documentos/"   = ""
"Documents/"   = ""
"Downloads/"   = ""
"Descargas/"   = ""
"Pictures/"    = ""
"Imágenes/"    = ""
"Music/"       = ""
"Musica/"       = ""
"Movies/"      = ""
"Videos/"      = ""
"Public/"      = ""
"Library/"     = ""
"Development/" = ""
".config/"     = ""

# Default
"*"  = ""
"*/" = ""
