# [flavor]
# dark = "gruvbox-dark"
# light = "gruvbox-dark"

[manager]
preview_hovered = { underline = false, bg = "#383838"}

[status]
# separator_open = "\ue0be"
# separator_close = "\ue0b8"
separator_open = " "
separator_close = " "
separator_style = { fg = "#3c3836", bg = "#3c3836" }

# Progress
progress_label = { fg = "#ebdbb2", bold = true }
progress_normal = { fg = "#504945", bg = "#3c3836" }
progress_error = { fg = "#fb4934", bg = "#3c3836" }

[mode]
normal_main = { fg = "#282828", bg = "#a89984", bold = true }
normal_alt = { fg = "#dddddd", bg = "#555555", bold = true }

select_main = { fg = "#282828", bg = "#fe8019", bold = true }
select_alt = { fg = "#dddddd", bg = "#555555", bold = true }

unset_main = { fg = "#282828", bg = "#b8bb26", bold = true }
unset_alt = { fg = "#dddddd", bg = "#555555", bold = true }


[filetype]

rules = [
    { mime = "image/*", fg = "#dddddd" },
    { mime = "video/*", fg = "#dddddd" },
    { mime = "audio/*", fg = "#dddddd"},

    # Archives
    { mime = "application/*zip", fg = "#fb4934" },
    { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#fb4934" },

    # Documents
    { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#689d6a" },

    # Fallback
    { name = "*", fg = "#ebdbb2" },
    { name = "*/", fg = "#83a598" },
]

[icons]

"Desktop/"     = ""
"Documentos/"   = ""
"Documents/"   = ""
"Downloads/"   = ""
"Descargas/"   = ""
"Pictures/"    = ""
"Imágenes/"    = ""
"Music/"       = ""
"Musica/"       = ""
"Movies/"      = ""
"Videos/"      = ""
"Public/"      = ""
"Library/"     = ""
"Development/" = ""
".config/"     = ""

# Default
"*"  = ""
"*/" = ""
