[manager]
layout         = [ 1, 3, 4 ]
sort_by        = "natural"
sort_sensitive = true
sort_reverse   = false
sort_dir_first = true
show_hidden    = false
show_symlink   = true

[preview]
tab_size   = 2
max_width  = 600
max_height = 800
cache_dir  = "~/.cache/yazi/"

[opener]
folder = [
    { exec = 'pcmanfm "$@"', block = true, display_name = "Pcmanfm" },
    { exec = '$EDITOR "$1"', block = true, display_name = "Editor" },
    { exec = 'zip comprimido.zip "$@"', display_name = "Compress" },
    { exec = '7z comprimido.7z "$@"', display_name = "Compress with 7z" },
    { exec = 'tm-ses "$1"', block = true, display_name = "Tmux session" },
]
archive = [
    { exec = 'unzip "$@"', display_name = "Extract here" },
    { exec = '7z x "$@"', display_name = "Extract with 7z" },
    { exec = 'xdg-open "$@"' },
]
text = [
    { exec = '$EDITOR "$@"', block = true },
    { exec = 'xdg-open "$@"', display_name = "Xdg-Open" },
]
image = [
    { exec = 'xdg-open "$@"', display_name = "Open" },
    { exec = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, display_name = "Show EXIF" },
    { exec = 'gimp "$@"', display_name = "Gimp" },
]
video = [
    { exec = 'xdg-open "$@"' },
    { exec = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, display_name = "Show media info" },
]
audio = [
    { exec = 'xdg-open "$@"' },
    { exec = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, display_name = "Show media info" },
]
fallback = [
    { exec = 'xdg-open "$@"', display_name = "Xdg-Open" },
    { exec = '$EDITOR "$@"', block = true, display_name = "Editor" },
    { exec = '7z comprimido.zip "$@"', display_name = "Zip" },
    { exec = '7z comprimido.7z "$@"', display_name = "Compress with 7z" },
]

[open]
rules = [
    { name = "*/", use = "folder" },

    { mime = "text/*", use = "text" },
    { mime = "image/*", use = "image" },
    { mime = "video/*", use = "video" },
    { mime = "audio/*", use = "audio" },
    { mime = "inode/x-empty", use = "text" },

    { mime = "application/json", use = "text" },
    { mime = "*/javascript", use = "text" },

    { mime = "application/zip", use = "archive" },
    { mime = "application/gzip", use = "archive" },
    { mime = "application/x-tar", use = "archive" },
    { mime = "application/x-bzip", use = "archive" },
    { mime = "application/x-bzip2", use = "archive" },
    { mime = "application/x-7z-compressed", use = "archive" },
    { mime = "application/x-rar", use = "archive" },

    { mime = "*", use = "fallback" },
]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[log]
enabled = false
