[manager]
layout         = [ 1, 3, 4 ]
sort_by        = "natural"
sort_sensitive = true
sort_reverse   = false
sort_dir_first = true
show_hidden    = false
show_symlink   = true

[preview]
tab_size   = 2
max_width  = 600
max_height = 800
cache_dir  = "~/.cache/yazi/"

[opener]
folder = [
    { run = 'xdg-open "$@"', desc = "Xdg-Open" },
    { run = 'tm-ses "$1"', block = true, desc = "Tmux session" },
]
archive = [
    { run = 'unzip "$@"', desc = "Unzip" },
    { run = '7z x "$@"', desc = "Extract with 7z" },
]
image = [
    { run = 'xdg-open "$@"', desc = "Xdg-Open" },
    { run = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show EXIF" },
    { run = 'gimp "$@"', desc = "Gimp" },
]
video = [
    { run = 'xdg-open "$@"', desc = "Xdg-Open" },
    { run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info" },
]
text = [
    { run = '$EDITOR "$@"', block = true, desc = "$EDITOR" },
]
audio = [
    { run = 'xdg-open "$@"', desc = "Xdg-Open" },
    { run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info" },
]
fallback = [
    # NOTE: mantener linea siempre arriba, asi siempre se usara "xdg-open" por defecto
    { run = 'xdg-open "$@"', desc = "Xdg-Open" },
    { run = '$EDITOR "$@"', block = true, desc = "$EDITOR" },
    { run = '7z a comprimido.zip "$@"', desc = "zip" },
    { run = '7z a comprimido.7z "$@"', desc = "7zip" },
    { run = 'dragon -a -x "$@"', desc = "Drag and drop" }
]

[open]
rules = [
    { name = "*/", use = "folder" },

    { mime = "text/*", use = "text" },
    { name = "*.md", use = "text" },
    { name = "*.markdown", use = "text" },
    { mime = "image/*", use = "image" },
    { mime = "video/*", use = "video" },
    { mime = "audio/*", use = "audio" },
    { mime = "inode/x-empty", use = "text" },

    { mime = "application/json", use = "text" },
    { mime = "*/javascript", use = "text" },

    { mime = "application/zip", use = "archive" },
    { mime = "application/gzip", use = "archive" },
    { mime = "application/x-tar", use = "archive" },
    { mime = "application/x-bzip", use = "archive" },
    { mime = "application/x-bzip2", use = "archive" },
    { mime = "application/x-7z-compressed", use = "archive" },
    { mime = "application/x-rar", use = "archive" },

    { mime = "*", use = "fallback" },
]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[log]
enabled = false
