#!/bin/env bash

icon="/usr/share/icons/Qogir/symbolic/status/night-light-symbolic.svg"

case "$1" in
    up)
        brightnessctl set 2%+ > /dev/null
        ;;
    down)
        brightnessctl set 2%- > /dev/null
        ;;
esac

IFS=',' read -r _ _ _ current_value _ < <(brightnessctl -m)
current_value="${current_value%\%}"

notify-send "Brightness" -h int:value:"$current_value" -i "$icon"
