[general]
import = [
    "/home/elias/.config/alacritty/keys.toml", 
    # "/home/elias/.config/alacritty/themes/thelovelace.toml"
    # "/home/elias/.config/alacritty/themes/taerminal.toml"
    # "/home/elias/.config/alacritty/themes/colorscheme.toml"
    # "/home/elias/.config/alacritty/themes/neovim.toml"
    "/home/elias/.config/alacritty/themes/gruvbox_material.toml"
    # "/home/elias/.config/alacritty/themes/oldworld.toml"
]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
family = "ComicShannsMono Nerd Font"

[font.offset]
x = 0
y = 4

[window]
dynamic_padding = true
opacity = 0.95

[window.padding]
x = 4
y = 0

# [font.bold]
# family = "Caskaydia Cove Nerd Font"
#
# [font.normal]
# family = "FiraCode Nerd Font"
# family = "ComicShannsMono Nerd Font"
#
# [font.bold_italic]
# family = "Caskaydia Cove Nerd Font"
#
# [font.italic]
# family = "Caskaydia Cove Nerd Font"
